SchemaVersion: "1.0"
SageMaker:
  PythonSDK:
    Modules:
      RemoteFunction:
        # role arn is not required if in SageMaker Notebook instance or SageMaker Studio
        # Uncomment the following line and replace with the right execution role if in a local IDE
        RoleArn: arn:aws:iam::891612587330:role/service-role/AmazonSageMaker-ExecutionRole-20241230T123665
        ImageUri: 429704687514.dkr.ecr.us-east-2.amazonaws.com/sagemaker-base-python-310:1.0 # Update region
        InstanceType: ml.g5.2xlarge
        Dependencies: ./requirements.txt
        IncludeLocalWorkDir: true
        CustomFileFilter:
          IgnoreNamePatterns: # files or directories to ignore
            - "*.ipynb" # all notebook files
            - "__pycache__"
            - ".conda" # all notebook files
